"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var funcionarios_1 = require("./funcionarios");
var gerentes_1 = require("./gerentes");
var empresa = new Empresa("tech soluçoes");
var funcionario01 = new funcionarios_1.default("joão", 30000, "desenvolvedor", 500);
var funcionario02 = new funcionarios_1.default("lucia", 3040, "analista", 2000);
var gerente1 = new gerentes_1.default("gabriel", "gerente", 4000, 1000);
var gerente2 = new gerentes_1.default("ana", "gerente", 13000, 6600);
empresa.adicionarFuncionarios(funcionario01);
empresa.adicionarFuncionarios(funcionario02);
empresa.adicionarFuncionarios(gerente1);
empresa.adicionarFuncionarios(gerente2);
console.log("funcionarios antes do aumento:");
empresa.listarFuncionarios();
funcionario01.aplicarAumento(10);
funcionario02.aplicarAumento(15);
gerente1.aplicarAumento(10);
gerente2.aplicarAumento(400);
console.log("\nfuncionarios apos o aumento:");
empresa.listarFuncionarios();
